### PR TITLE
Add `key-fetcher` Middleware to Intercept and Map App Keys

### PR DESCRIPTION
**Pull request by garyhai**
### Introduction

This commit adds functionality to intercept and map the `app key` in client requests. By introducing a `key-fetcher` middleware during request processing, it extracts the client's `app key` from the `Authorization` header and replaces it with the actual `app key` from the provider. Additionally, a `TimedMap` caching mechanism is implemented to cache fetched `app keys`, improving performance.

### Main Changes

1. **Added `key_mapper` Module**

   - Created the `interceptors/key_mapper.rs` file, implementing the `key_fetcher` function.
   - Utilized `once_cell::sync::Lazy` and `timedmap::TimedMap` to create the static cache `APP_KEY_CACHE`.

2. **Modified Middleware Layer**

   - In `main.rs`, introduced the new middleware using `middleware::map_request_with_state`:
     ```rust
     .route_layer(middleware::map_request_with_state(config.clone(), key_fetcher))
     ```

3. **Implemented `key_fetcher` Functionality**

   - Extracted the client's `app key` from the `Authorization` header in the request.
   - Checked if the corresponding provider's `app key` exists in the cache; if so, used it directly.
   - If not in the cache, fetched the provider's `app key` from the configured `fetcher` URL.
   - Cached the fetched `app key` with a validity period of 1 hour.
   - Replaced the `Authorization` header in the request with the provider's `app key`.

## Summary by CodeRabbit

- **New Features**
	- Introduced a new configuration option for fetching application keys from the environment.
	- Added a key mapping module to enhance HTTP request handling.
	- Integrated middleware for improved request processing.
	- Added a new dependency to support enhanced functionality.

- **Bug Fixes**
	- Ensured proper formatting in the configuration file.

- **Documentation**
	- Updated documentation for the new key mapping functionality with examples.

### CODE REVIEW

**Comment by imshashank** [comment]
@garyhai Hi, can you please elaborate on why we need a key-fetcher for this repo. Wouldnt that make the gateway way less secure if you can get the API keys via an API?

**Comment by garyhai** [comment]
Thank you @imshashank for your inquiry regarding the necessity of a key-fetcher in this repository. I appreciate the opportunity to elaborate on its purpose and address your security concerns.

## Purpose of the Key-Fetcher

In developing AI frontend applications, particularly web-based ones, it’s crucial to conceal sensitive information such as App Keys. A common solution is to implement a backend service that proxies requests to AI providers. As AI applications grow in complexity, with more intricate interfaces and higher performance demands (e.g., support for streaming), developing such backend gateway services becomes increasingly challenging. I believe this is the motivation behind the design of ai-gateway. AI application developers greatly benefit from components like ai-gateway, which enhance development efficiency and reduce complexity.

Beyond hiding App Keys, developers often need to implement a traffic pool that supports multiple service providers and App Keys, due to quota limitations imposed by AI service providers. AI applications typically have their own user registration and login mechanisms, managing user sessions and authorizations. This setup allows developers to use AI providers’ network interfaces directly on the client side without complex encapsulation or performance concerns. One of ai-gateway’s impressive features is its unified OpenAI interface that supports various AI service providers.

## Extending Business Logic

Business-specific logic should not be implemented directly within ai-gateway, yet the gateway needs to handle such tasks. While extending business logic through plugins is an option, it can limit the choice of programming languages, increase development complexity, and prevent the use of existing business logic modules. The key-fetcher addresses this by interacting with business logic through a loosely coupled standard HTTP interface, allowing for greater flexibility and maintainability.

## Security Considerations

The key-fetcher is designed to interact with business logic through a loosely coupled standard HTTP interface. It is typically deployed on the same node or within the same internal network as ai-gateway. Therefore, it employs performance and security-sensitive implementations, such as the Axum middleware. As a backend network component, ai-gateway’s security relies on network topology and internal maintenance services, which are not directly exposed to external users.

I hope this clarifies the rationale behind introducing the key-fetcher and addresses your security concerns. Please let me know if you have any further questions or require additional information.

**Comment by imshashank** [comment]
Hi,

Sorry, but you haven't answered my questions.
Please explaining in 2 lines what this does, why we need to cache the keys? Wouldn't this actually make the whole gateway unsafe and also why can't we just read keys from headers?

**Comment by garyhai** [comment]
1. The key-fetcher allows using OpenAI APIs directly from the web frontend without exposing the OpenAI app key.
2. It doesn’t cache keys; it maps the JWT token from the frontend to an OpenAI app key via an HTTP service on the backend.

**Comment by garyhai** [comment]
I have realized that this PR may be too restrictive and that considering such an extension for the project at this stage is premature. Therefore, I have decided to close this pull request. I hope the ideas presented can still offer some valuable insights for the project’s future development.

**Pull request closed without merging**
